{{
  config(
    database='DEV_PG_RDS_REPLICATION',
    schema='POSTGRES_STREAMS',
    materialized='table',
  )
}}


SELECT "DATABASE", "TABLE", DATA FROM "DEV_PG_RDS_REPLICATION"."POSTGRES_STREAMS".PG_KAFKA_STREAM